#! v1.24.9---vmware.1-tkg.4
#! v1.25.7---vmware.3-fips.1-tkg.1
#! v1.26.5---vmware.2-fips.1-tkg.1

apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tap-cluster
#  namespace: tkgs-cluster-ns
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-medium
      storageClass: k8s-storage-policy
      tkr:  
        reference:
          name: v1.25.7---vmware.3-fips.1-tkg.1
    nodePools:
    - name: tap-worker-nodepool-a1
      replicas: 4
      vmClass: best-effort-xlarge
      storageClass: k8s-storage-policy
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 50Gi
      tkr:  
        reference:
          name: v1.25.7---vmware.3-fips.1-tkg.1
  settings:
    storage:
      defaultClass: k8s-storage-policy
    network:
      cni:
        name: antrea
      services:
        cidrBlocks: ["198.53.100.0/16"]
      pods:
        cidrBlocks: ["192.0.5.0/16"]
      trust:
        additionalTrustedCAs:
          - name: Planet10Lab
            data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVlakNDQXVLZ0F3SUJBZ0lSQUxHU3ZTQlhzb200OUNWaU5XcmxPUnN3RFFZSktvWklodmNOQVFFTEJRQXcKVlRFZU1Cd0dBMVVFQ2hNVmJXdGpaWEowSUdSbGRtVnNiM0J0Wlc1MElFTkJNUlV3RXdZRFZRUUxEQXh3YVhadgpkR0ZzUUhWa1pYWXhIREFhQmdOVkJBTU1FMjFyWTJWeWRDQndhWFp2ZEdGc1FIVmtaWFl3SGhjTk1qQXdOVEk0Ck1UWXhOekEzV2hjTk16QXdOVEk0TVRZeE56QTNXakJWTVI0d0hBWURWUVFLRXhWdGEyTmxjblFnWkdWMlpXeHYKY0cxbGJuUWdRMEV4RlRBVEJnTlZCQXNNREhCcGRtOTBZV3hBZFdSbGRqRWNNQm9HQTFVRUF3d1RiV3RqWlhKMApJSEJwZG05MFlXeEFkV1JsZGpDQ0FhSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnR1BBRENDQVlvQ2dnR0JBTWRaCjZHc2ZNYnpFdEtidGFTUTVOSFpYeEUvTG5uWThrTzVrTUFjOXR2Rzd4aEt6Q1JFZWh3cUN2emF1MHdwdVdDalUKNkZaUEZhbDZ4QTdPRHlabVJmYkhGRFZkVGhpT2gzV01qT2JFdm1KVVJnaTZRUGxTcFNiazBzMmZOYUcva1pEUAp0eEhmUW1yYVk0SlBvbUhrdUNzUkpJTGh2ajZSQzIrcElQWWRsNlB2OW1KQnh1WmpLNTRvVzdtUWFKaVdCdnFXCk9MVUFQZk5LeVY5Qis5SGZIb3dLZEwybk8yUXQwRllUTFE4SHZwQkgzUTNDZ0F0VjZSQkJlUFBnMmlCZDdURFcKUHB0ZXZNMDAwdnFUYTBmbDRXdEw3SEgydjNKTnlGT2xqbzB0S0FKZ3p5bVVRUjNISmo5dUZydVNRV1Nqb3B0eQpYVlQxdzlzSmpUZXdsajJsSWk3Rk56MkRNWnRXYkpjNkUzOWFqU3ovcmltUTJ5Y2RuT0lLN0RzWS9XZVJ6TWh4CkE0b29HcThnOHdjK1dwbVJSYWVYeWpvSTZuMklCVDVoaVN3alVWOFNWMmlJOEovakdjS0R1NlcrbnVpV3JvN2kKb1lobkVrZ2h5L2wwVG1WbmNTUTFPRkNqdjFkRHlDbm9UR0RvWGNHMXZNc09VaUdyb3R4Mkd2dUp5eU5peFFJRApBUUFCbzBVd1F6QU9CZ05WSFE4QkFmOEVCQU1DQWdRd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFEQWRCZ05WCkhRNEVGZ1FVb0cxUnZVaE9yM0dDYjZPbWxHOXhOSC83VGt3d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFKN3UKV0Jpc0lPVGQ4VFpER1VNdndKSGRQMHFKL0ZKL0ozeXEvTDNEZU16cFFmZTJEOTZNMFI2TUoySjFXSzEzUGdoSwp0U3hhaFY2QXJHdnlnazlhTis3dEp3eTBQNW1MVFFPQStLTjhIS1JPR2tVTUw1SFk2QUE2blZuUEpZVVhvMm5YCjRaZHh4NUZUQlludEdJWW93UE5acHlNb1dWQnZxYnhzcEdPYlhaWXhMb0tpQlVlRzVEMjZMekh5WlM1MHd5Y2EKdFBlTzFQalc1MlJTNDluZUdBZ2VIK08rMEJ3a1lUY1dvQWpVcXJPalVITFh5Y09jMlc3YkJpUUphWlNHdlZtUAo4RnhpcXkyWU85V1Rvd0hyWDkxdkhPeVRBRW56aFhvRWN3aXZ3bzdTT1Rab21OekV5TThqbnY1K3ljVDBZZzNhCnFhSmIzRFlvc0VsMHZrTC9Fa1ZMNnd2YkNwK3cyclhKQzBkR3Y2N0dCK1hyRjNnQ2dmZGh1QittU05hd1FzMG0KbHpSdTI2UkJwWkxIdUZsZnQyTFVZMXBsVm1RcnREU2RTK3RBbmRYSjd0NUN3SFRFMDJrbjNobGI4WkJiS09ibgpzL2VLSkZGbTF4SU1IWXJBTTVnazFXVmllRm5iR2R4TVpoYlBVak05Q1lBVUFWVkpoN05GM3NtS05WeDVrUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
