#! tap-values.yml
#! base file for generating a tap-values file by overlaying with ytt
#! depends on tap-values-value-schema.yml, my_functions.star, and a file with registry details

#@ load("@ytt:data", "data")
#@ load("my_functions.star", "host_path")

shared:
  ingress_domain: "tap.tkgs.planet10.lab"
  image_registry:
    project_path: #@ host_path(data.values.registry.hostname, "tap/projects")
    secret:
      name: #@ data.values.registry.secret.name
      namespace: #@ data.values.registry.secret.namespace
  ca_cert_data: #@ data.values.ca_cert_data

profile: full
ceip_policy_disclosed: true

namespace_provisioner:
  controller: true

buildservice:
  #! kp_default_repository: #@ host_path(data.values.registry.hostname, data.values.registry.buildservice_repository)
  #! kp_default_repository_username: #@ data.values.registry.username
  #! kp_default_repository_password: #@ data.values.registry.password
  #! exclude_dependencies: true

supply_chain: basic

scanning:
  metadataStore:
    url: ""

contour:
  envoy:
    service:
      type: LoadBalancer

ootb_supply_chain_basic:
  registry:
      server: #@ data.values.registry.hostname
      repository: #@ data.values.registry.tap_repository
  #! gitops:
  #!     ssh_secret: "SSH-SECRET"
  #! maven:
  #!     repository:
  #!        url: https://MAVEN-URL
  #!        secret_name: "MAVEN-CREDENTIALS"

accelerator:
  ingress:
    include: true
    enable_tls: false
  #! git_credentials:
  #!   secret_name: git-credentials
  #!   username: GITLAB-USER
  #!   password: GITLAB-PASSWORD

appliveview:
  ingressEnabled: true
  #! tls:
  #!   secretName: "SECRET-NAME"
  #!   namespace: "APP-LIVE-VIEW-NAMESPACE"

appliveview_connector:
  backend:
    ingressEnabled: true
    sslDisabled: true

tap_gui:
  service_type: ClusterIP
  app_config:
    auth:
      environment: development
      providers:
        github:
          development:
            clientId: #@ data.values.auth.github.clientId
            clientSecret: #@ data.values.auth.github.clientSecret
        #! gitlab:
        #!   development:
        #!     clientId: #@ data.values.auth.gitlab.clientId
        #!     clientSecret: #@ data.values.auth.gitlab.clientSecret
    #! kubernetes:
    #!   serviceLocatorMethod:
    #!     type: multiTenant
    #!   clusterLocatorMethods:
    #!     - type: config
    #!       clusters:
    #!         - url: https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}
    #!           name: host
    #!           authProvider: serviceAccount
    #!           serviceAccountToken: ${KUBERNETES_SERVICE_ACCOUNT_TOKEN}
    #!           skipTLSVerify: false
    #!           caData: B64_ENCODED_CA
    catalog:
      locations:
        - type: url
          target: https://github.com/sdeeg-vmware/tap-gui-catalog/blob/master/catalog-info.yaml
    #!Example Integration for custom GitLab:
    #! integrations:
    #!   gitlab:
    #!     - host: GITLABURL
    #!       token: <GITLAB-TOKEN>
    #!       apiBaseUrl: https://GITLABURL/api/v4/
    #! backend:
    #!   reading:
    #!     allow:
    #!       - host: https://GIT-CATALOG-URL/catalog-info.yaml

metadata_store:
  #! ns_for_export_app_cert: "MY-DEV-NAMESPACE"
  app_service_type: ClusterIP

grype:
  namespace: "grype" #! (optional) Defaults to default namespace.
  targetImagePullSecret: "registry-secret"

excluded_packages:
  - policy.apps.tanzu.vmware.com