#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("my_functions.star", "host_path")

#@overlay/match by=overlay.all
#@overlay/merge
---
shared:
  image_registry:
    project_path: #@ host_path(data.values.registry.hostname, "tap/projects")
    username: #@ data.values.registry.username
    password: #@ data.values.registry.password
  ca_cert_data: #@ data.values.ca_cert_data

buildservice:
  kp_default_repository: #@ host_path(data.values.registry.hostname, data.values.registry.buildservice_repository)
  kp_default_repository_username: #@ data.values.registry.username
  kp_default_repository_password: #@ data.values.registry.password

ootb_supply_chain_basic:
  registry:
      server: #@ data.values.registry.hostname
      repository: #@ data.values.registry.tap_repository
