apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sqlrunner
  namespace: development
  labels:
    app.kubernetes.io/part-of: sqlrunner
    apps.tanzu.vmware.com/workload-type: web
spec:
  image: registry.planet10.lab/apps/sqlrunner:1.0
  # source:
  #   git:
  #     ref:
  #       branch: main
  #     url: https://github.com/sdeeg-vmware/sqlrunner.git